### PR TITLE
Create pl_pl.json

### PR DESCRIPTION
**Pull request by K0-RR**

### CODE REVIEW

**Comment by K0-RR** [comment]
Hi, I'm not sure what happened with this pr, like why aren't the commits visible anymore? Why are here commits others than mine? What about adding pl_pl?

**Comment by vini2003** [comment]
I fucked up.

**Comment by vini2003** [comment]
I'm migrating this project to Architectury for Forge support. Once I get that working, please re-submit it. I pushed the wrong branch to master, sorry.

**Comment by K0-RR** [comment]
Seems like the architectury version is working so resubmitting.

**Comment by K0-RR** [comment]
Or at least I would like to...
image

Why can't I create a pr?

**Pull request closed without merging**
